# This workflow will upload a Python Package to PyPI when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: cypm

on:
  [push]

permissions:
  contents: read

jobs:
  release-build:
    runs-on: windows_latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Build release distributions
        run: |
          # NOTE: put your own distribution build steps here.
          python -m pip install nuitka openpyxl PySide2 BlurWindow
          nuitka --standalone --onefile --follow-imports --windows-disable-console --windows-icon-from-ico=图标.ico chouyipaoming.py

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/
